### ISSUE TITLE
Апи 2гиса

### ISSUE THREAD

**Issue by L3XxXa** [L3XxXa/Alpha-bank-hackaton#2]
Посмотреть апишку 2гиса, поискать, что нам нужно оттуда достать.

**Comment by Fagorym** [comment]
Нужен Places API, который будем формировать по следующему шаблону
https://catalog.api.2gis.com/3.0/ + параметры
Нужные нам параметры:
sort_point = точка, местоположение нашего юзера, от которой будет идти фильтрация результатов
sort = distance, это значит, что фильтрация будет проходить по дистанции
fields = .... Поля, которые нам нужно достать, скорее всего только название и координаты
key = API Ключ
q = ... Поисковая строка, например, "Магазин", "Лента", "Кафе" и т.д.
Вот пример такого запроса 
https://catalog.api.2gis.com/3.0/items?q=магазин&sort_point=83.0906156, 54.8439935&key=<API>&sort=distance&fields=items.point, items.address, items.rubricks

**Comment by L3XxXa** [comment]
Сделай страничку внутри ноушена, чтобы проще потом было найти это

**Comment by Fagorym** [comment]
https://www.notion.so/2gis-API-e7b0348ede904aef9beb1ab7e91d1b17

**Comment by L3XxXa** [comment]
Пойдет
