### ISSUE TITLE
Макет для страницы аутентификации

### ISSUE THREAD

**Issue by L3XxXa** [L3XxXa/Alpha-bank-hackaton#4]
Создать макет

**Comment by L3XxXa** [comment]
Что нам надо: 
Два EditText на логин и пароль
Пароль с чекбоксом на видимость/невидимость
Кнопка Войти
Кнопка Зарегистрироваться
Кнопка Восстановить Пароль

**Comment by L3XxXa** [comment]
![image](https://user-images.githubusercontent.com/71200647/205100668-bf1e7d46-3c2e-46cf-b7b7-9383a6fda286.png)
каркас такой

**Comment by L3XxXa** [comment]
![Screenshot_20221204-022035.png](https://user-images.githubusercontent.com/71200647/205458149-847717aa-ac05-4c39-8d86-90ca8cc9040a.png) я пока сделал такое

**Comment by Tretiakovv** [comment]
Сделал готовые макеты в Figma. В секции «Components» можешь увидеть сценарии разных состояний форм.
